name: topic_modeling
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - attrs=19.3.0
  - backcall=0.1.0
  - bleach=3.1.4
  - brotlipy=0.7.0
  - ca-certificates=2020.4.5.1
  - catalogue=1.0.0
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - chart-studio=1.1.0
  - colorlover=0.3.0
  - cryptography=2.8
  - cufflinks-py=0.17.3
  - cycler=0.10.0
  - cymem=2.0.3
  - cython-blis=0.4.1
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.10.1
  - funcy=1.14
  - future=0.18.2
  - icu=58.2
  - idna=2.9
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - ipykernel=5.2.1
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.0
  - jinja2=2.11.2
  - joblib=0.14.1
  - jpeg=9c
  - jsonschema=3.2.0
  - jupyter_client=6.1.3
  - jupyter_core=4.6.3
  - kiwisolver=1.2.0
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libsodium=1.0.17
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libwebp-base=1.1.0
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - murmurhash=1.0.0
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.2
  - nltk=3.4.4
  - notebook=6.0.3
  - numexpr=2.7.1
  - numpy=1.18.1
  - olefile=0.46
  - openssl=1.1.1g
  - pandas=1.0.3
  - pandoc=2.9.2.1
  - pandocfilters=1.4.2
  - parso=0.7.0
  - patsy=0.5.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=20.0.2
  - plac=0.9.6
  - plotly=4.6.0
  - preshed=3.0.2
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.5
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyldavis=2.1.2
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.7.7
  - python-cufflinks=0.17.3
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2019.3
  - pyzmq=19.0.0
  - readline=8.0
  - requests=2.23.0
  - retrying=1.3.3
  - scikit-learn=0.22.2.post1
  - scipy=1.4.1
  - seaborn=0.10.0
  - send2trash=1.5.0
  - setuptools=46.1.3
  - six=1.14.0
  - spacy=2.2.3
  - sqlite=3.31.1
  - srsly=1.0.0
  - statsmodels=0.11.1
  - terminado=0.8.3
  - testpath=0.4.4
  - thinc=7.3.0
  - tk=8.6.8
  - tornado=6.0.4
  - tqdm=4.45.0
  - traitlets=4.3.3
  - urllib3=1.25.9
  - wasabi=0.6.0
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - wordcloud=1.6.0
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4

